assets/aled.ogg
assets/arial.ttf
assets/auberge.png
assets/Aubergiste.png
assets/Augusta.ttf
assets/Augusta-Shadow.ttf
assets/back_music.ogg
assets/bato.png
assets/church.png
assets/credit_en.png
assets/doors.png
assets/down_vol.png
assets/eng.png
assets/ennemi.png
assets/exterior_ground.png
assets/font.ttf
assets/forge.png
assets/fr.png
assets/hero.png
assets/hero_hitbox.png
assets/how_to_play_en.png
assets/how_to_play_fr.png
assets/hurt.ogg
assets/inventory/grid.png
assets/inventory/inv.png
assets/inventory/inv1.png
assets/inventory/inv2.png
assets/inventory/inv3.png
assets/items/shield.png
assets/items/sword.png
assets/items.png
assets/items2/item_boomerang.png
assets/items2/item_boots.png
assets/items2/item_boots_chain.png
assets/items2/item_chestplate.png
assets/items2/item_chestplate.png
assets/items2/item_double_axe.png
assets/items2/item_flail.png
assets/items2/item_hammer.png
assets/items2/item_heavy_shield.png
assets/items2/item_helmet.png
assets/items2/item_helmet_chain.png
assets/items2/item_hoe.png
assets/items2/item_knife.png
assets/items2/item_left_glove.png
assets/items2/item_legings.png
assets/items2/item_legings_chain.png
assets/items2/item_pickaxe.png
assets/items2/item_right_glove.png
assets/items2/items.png
assets/items2/item_shield.png
assets/items2/item_shovel.png
assets/items2/item_spear.png
assets/items2/item_speared_axe.png
assets/items2/item_sword.png
assets/items2/item_tomahawk.png
assets/loading_en.png
assets/loading_fr.png
assets/maison1.png
assets/maison2.png
assets/maison3.png
assets/maison4.png
assets/maison5.png
assets/map.txt
assets/map_hitbox.png
assets/menu_font.ttf
assets/menu_font_h.ttf
assets/menu_image.png
assets/mort.png
assets/normal_dummy.png
assets/option_key_en.png
assets/option_key_fr.png
assets/parchemin.png
assets/perso_blanc.png
assets/perso_vert.png
assets/stupid_nathan.png
assets/TileA2_exterior.png
assets/TileA3.png
assets/TileB_exterior4.png
assets/TileC_exterior.png
assets/TileD_exterior1.png
assets/TileD_exterior3.png
assets/TileD_interior.png
assets/up_vol.png
assets/Water_things.png
assets/assets_data.ini
assets/inv.ini
assets/Forgeron.png